### PR TITLE
TTP223 sensor added

### PR DESCRIPTION
**Pull request by jeanmatthieud**
UPM example :
https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/ttp223.js

Intel doc :
http://iotdk.intel.com/docs/master/upm/classupm_1_1_t_t_p223.html

### CODE REVIEW

**Comment by jeanmatthieud** [comment]
Missing files

**Comment by deadprogram** [comment]
Hi, @jeanmatthieud 

This looks cool, also check out the branch https://github.com/hybridgroup/cylon-intel-iot/compare/feature/add-upm-devices that we have going. The `TTP223` is not one of the sensors we're adding in that branch, so you adding it is great!

Awaiting your replacement PR... thank you!

**Comment by jeanmatthieud** [comment]
Hi,

I'm trying to add UPM sensor on the "add-upm-devices" branch.
I edited the index.js file and the upm-sensor.js file. Sadly, it doesn't work on my Edison card with cylon. Do I have to edit another file ?

**Comment by deadprogram** [comment]
That should be all that is needed. Check your version of UPM/MRAA, also check to make sure you are running your test code on the cylon-intel-iot feature branch, and not the master.

**Comment by jeanmatthieud** [comment]
When I use the UPM module without cylon, I can use the sensor (it works).
When I use the code of my fork (the branch), when cylon starts, I see something like "Start 'fonction () { [ native code ] }' on pin 3" instead of "Start 'ttp223' on pin 3".
It's weird...

**Pull request closed without merging**
